poetry.lock, pyproject.toml
=> Set aiortc version to 1.0.0

app.py
https://github.com/whitphx/streamlit-webrtc/issues/44#issuecomment-796563540
Thank you, @superwhyun !
=> Fix app.py to break the loop correctly

CHANGELOG.md, streamlit_webrtc/__init__.py
=> Fix to instantiate SessionState to be properly bound to session

streamlit_webrtc/transform.py, streamlit_webrtc/webrtc.py
=> Set thread names

CHANGELOG.md, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx
=> Hide <DeviceSelector /> if mode is RECVONLY

CHANGELOG.md, streamlit_webrtc/frontend/src/DeviceSelector.tsx, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx
=> Hide video/audio from <DevicSelector /> if unused

CHANGELOG.md, streamlit_webrtc/__init__.py
=> Fix to rerun the script to unset the worker after stopping

CHANGELOG.md, streamlit_webrtc/SessionState.py
=> Fix SessionState to have a unique ID

CHANGELOG.md, app.py, streamlit_webrtc/__init__.py, streamlit_webrtc/config.py, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx, streamlit_webrtc/frontend/src/media-constraint.ts, streamlit_webrtc/frontend/src/media-constraints.test.ts
=> Add complex MediaStreamConstrants

CHANGELOG.md, app.py, streamlit_webrtc/webrtc.py
Resolves #145
Related to #202
---
Sample code to consume RTSP stream and apply filters to it in RECVONLY mode.
```python
def create_player():
return MediaPlayer(
"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
)
class OpenCVVideoProcessor(VideoProcessorBase):
type: Literal["noop", "cartoon", "edges", "rotate"]
def __init__(self) -> None:
self.type = "noop"
def recv(self, frame: av.VideoFrame) -> av.VideoFrame:
img = frame.to_ndarray(format="bgr24")
if self.type == "noop":
pass
elif self.type == "cartoon":
img_color = cv2.pyrDown(cv2.pyrDown(img))
for _ in range(6):
img_color = cv2.bilateralFilter(img_color, 9, 9, 7)
img_color = cv2.pyrUp(cv2.pyrUp(img_color))
img_edges = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
img_edges = cv2.adaptiveThreshold(
cv2.medianBlur(img_edges, …
```
=> Update to make processors effective in RECVONLY mode with a player

CHANGELOG.md, streamlit_webrtc/process.py
=> Fix AsyncMediaProcessTrack to be stopped when the input track stopped

CHANGELOG.md, app.py, streamlit_webrtc/__init__.py, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx
=> Add desired_playing_state

CHANGELOG.md, streamlit_webrtc/__init__.py
=> hotfix: marshal the component value if it is of type str

CHANGELOG.md, streamlit_webrtc/__init__.py
=> Revert a change in #278

CHANGELOG.md, streamlit_webrtc/SessionState.py, streamlit_webrtc/__init__.py
=> Save component value to be restored after rerun

CHANGELOG.md, app.py, streamlit_webrtc/__init__.py, streamlit_webrtc/component.py, streamlit_webrtc/config.py, streamlit_webrtc/frontend/src/MediaStreamPlayer.tsx, streamlit_webrtc/frontend/src/Placeholder.tsx, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx
* Runtime type checking to avoid server-side injection
Resolves #271
=> Control media html attributes

streamlit_webrtc/process.py, streamlit_webrtc/receive.py
Ref: https://github.com/python/asyncio/issues/477#issuecomment-268709555
=> Use loop.create_task instead of asyncio.ensure_future

CHANGELOG.md, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx, streamlit_webrtc/frontend/src/component-value.ts
=> Fix frontend to set componentValue when mounted

CHANGELOG.md, streamlit_webrtc/process.py
=> Mark async-processor threads as daemon

streamlit_webrtc/frontend/src/ThemeProvider.tsx, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx, streamlit_webrtc/frontend/src/index.tsx
=> Fix <ThemeProvider /> to use useRenderData()

streamlit_webrtc/frontend/package-lock.json, streamlit_webrtc/frontend/package.json, streamlit_webrtc/frontend/src/DeviceSelector.tsx, streamlit_webrtc/frontend/src/Placeholder.tsx, streamlit_webrtc/frontend/src/ThemeProvider.tsx, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx, streamlit_webrtc/frontend/src/index.tsx
=> Upgrade MaterialUI to v5

CHANGELOG.md, pyproject.toml, streamlit_webrtc/factory.py, streamlit_webrtc/session_info.py, streamlit_webrtc/shutdown.py
=> Rename imported module and methods for streamlit>=1.4

CHANGELOG.md
=> Touch streamlit_webrtc/py.typed

README.md
=> Update CHANGELOG.md about logging

CHANGELOG.md, app.py, streamlit_webrtc/component.py, streamlit_webrtc/models.py, streamlit_webrtc/process.py, streamlit_webrtc/webrtc.py
=> Class-less callbacks replacing the processor classes

streamlit_webrtc/models.py, streamlit_webrtc/webrtc.py
=> Fix CallbackAttachableProcessor to be thread-safe

poetry.lock, pyproject.toml
- Upgrade streamlit for dev to ^1.10.0
- Specify the numpy version for dev env
=> dev/upgrade dev streamlit 1.10.0

CHANGELOG.md, app_multi.py, app_videochat.py, streamlit_webrtc/__init__.py, streamlit_webrtc/factory.py, streamlit_webrtc/mix.py, streamlit_webrtc/models.py
=> Class-less mixer callback

.github/workflows/main.yml, CHANGELOG.md, poetry.lock, pyproject.toml, streamlit_webrtc/eventloop.py, streamlit_webrtc/relay.py, streamlit_webrtc/server.py, streamlit_webrtc/session_info.py, streamlit_webrtc/shutdown.py, tests/session_info_test.py
=> Upgrade streamlit as a dev dep to 1.12.0 and fix imports

.github/workflows/main.yml, CHANGELOG.md, poetry.lock, pyproject.toml, streamlit_webrtc/eventloop.py, streamlit_webrtc/server.py, streamlit_webrtc/session_info.py, tests/session_info_test.py
=> fix/compatibility streamlit 1.12.1

CHANGELOG.md, streamlit_webrtc/server.py
=> Add try-except to catch ReferenceError during searching the server object

.github/workflows/main.yml
=> Fix the CI workflow for poetry to create the local venv

CHANGELOG.md, streamlit_webrtc/webrtc.py
=> Use MediaRelay with SENDONLY mode to avoid wrong frame synchronization

.github/workflows/main.yml, pages/1_object_detection.py, poetry.lock, streamlit_webrtc/eventloop.py, streamlit_webrtc/factory.py, streamlit_webrtc/mix.py, streamlit_webrtc/relay.py, streamlit_webrtc/server.py, streamlit_webrtc/session_info.py, streamlit_webrtc/webrtc.py
=> dev/streamlit 1.18.0

poetry.lock, pyproject.toml
Python 3.7 is no longer supported.
=> Fix pandas ver

.github/workflows/main.yml, streamlit_webrtc/_compat.py, streamlit_webrtc/component.py
Rel: https://github.com/whitphx/streamlit-webrtc/issues/1848#issuecomment-2585658507
=> Fix the bug that streamlit-webrtc doesn't work since Streamlit 1.39.0 by fixing the frontend callback registration

.github/workflows/main.yml
based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> Update the publish jobs

CHANGELOG.md, app_deepspeech.py, app_videochat.py, streamlit_webrtc/component.py, streamlit_webrtc/frontend/src/WebRtcStreamer.tsx, streamlit_webrtc/frontend/src/webrtc/index.ts
#1943 was incomplete.
We need to configure both the frontend and the server side correctly about the STUN/TURN servers.
=> RTCConfiguration both for frontend and server side

streamlit_webrtc/webrtc.py
=> Use asyncio.run_coroutine_threadsafe instead of loop.create_task

streamlit_webrtc/component.py, streamlit_webrtc/frontend/src/component-value.ts, streamlit_webrtc/frontend/src/webrtc/actions.ts, streamlit_webrtc/frontend/src/webrtc/index.ts, streamlit_webrtc/frontend/src/webrtc/reducer.ts, streamlit_webrtc/webrtc.py
=> Frontend Trickle ICE

pyproject.toml, uv.lock
Ref: https://github.com/aiortc/aioice/pull/84
=> Use a patched version of aioice to address the ICE issue

streamlit_webrtc/component.py
=> Set the worker to the context object before calling process_offer() to avoid duplicated worker creation

streamlit_webrtc/frontend/src/WebRtcStreamer.tsx
=> Show a warning when it takes long to initiate the connection

streamlit_webrtc/component.py, streamlit_webrtc/webrtc.py
=> Make the worker creation atomic

streamlit_webrtc/component.py
=> Lock process_offer() and rerun() so that the rerun() works properly

streamlit_webrtc/component.py
=> Fix to make rerun() effective when fastReruns is enabled

.claude/settings.local.json, CLAUDE.md, pages/15_audio_source.py, streamlit_webrtc/__init__.py, streamlit_webrtc/component.py, streamlit_webrtc/factory.py, streamlit_webrtc/source.py
=> AudioSourceTrack by Claude Code

streamlit_webrtc/component.py
Resolves #2119 (this PR doesn't use a lock but the Streamlit's caching mechanism should have the same effect)
=> Fix rtc_configuration getter impl
